POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Paul Smith",
    "number": "07932496666"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "this is the content"
}

###

GET http://localhost:3001/api/persons
content-type:application/json

###

GET http://localhost:3001/api/persons/someInvalidID
content-type: application/json

###


GET http://localhost:3001/info
content-type: application/json

###

PUT http://localhost:3001/api/persons/6154af54a5d9072363ea3bb3
content-type: application/json

{
    "number": "01323-440923"
}